### PR TITLE
Improve pen detection on Linux

### PR DESCRIPTION
**Pull request by luboslenco**
(thanks to https://github.com/armory3d/armorpaint/issues/707#issuecomment-1337550352)

### CODE REVIEW

**Comment by UnoCastillo** [comment]
Please help. i just compile Armorpaint today but my xp pen pro presure doesn´t work. how can i make this works?
i just fllow a tut for compile, i am not to good at this "code" fixes.

**Comment by RobDangerous** [comment]
Try posting in armory3d/armorpaint#707 - your message will be lost here and I can't help because I do not have an xp pen pro pressure (or any pen at all for my computers).

**Comment by UnoCastillo** [comment]
i tryed to do so, but that subject it is closed.

**Comment by UnoCastillo** [comment]
@luboslenco can you please give me a hand on this?

**Pull request merged**
