### PR TITLE
Linux gamepad support, initial minimial implementation

### PR DESCRIPTION
**Pull request by guzzard**
Hi @RobDangerous, second attempt! :smiley:. This is an initial minimal implementation based on kernel documentation only. Tested in a Kha project and in an Armory project, seem to work fine!

### CODE REVIEW

**Comment by RobDangerous** [comment]
Oh, that looks really nice!

**Comment by guzzard** [comment]
Awesome! :+1:

**Comment by RobDangerous** [comment]
I replaced the std::string usage (makes it compile faster and on old compilers (it failed on travis for that reason)), please test if it still works for you.

**Comment by guzzard** [comment]
Works fine!

**Pull request merged**
