### PR TITLE
[Android] Unicode keyboard input.

### PR DESCRIPTION
**Pull request by Sanva**
This enables Unicode input in Android.

Video testing it (with Kha) in a POCO X3 → https://www.youtube.com/watch?v=rcWiPZtRvcI .

### CODE REVIEW

**Comment by Sanva** [comment]
It looks like there is an error...

```
CMakeFiles/kinc.dir/home/runner/work/Kinc/Kinc/Backends/System/Android/Sources/kinc/backend/system.cpp.o -c /home/runner/work/Kinc/Kinc/Backends/System/Android/Sources/kinc/backend/system.cpp
  /home/runner/work/Kinc/Kinc/Backends/System/Android/Sources/kinc/backend/system.cpp:3:10: fatal error: 'hx/CFFI.h' file not found
  #include <hx/CFFI.h>
           ^~~~~~~~~~~
  1 error generated.
```

I'm not sure why this compiles in my system and not in CI... :thinking: .

**Comment by RobDangerous** [comment]
Because you included a Haxe header in Kinc. Doing Haxe GC things in a JNI function also doesn't make much sense.

**Comment by Sanva** [comment]
The thing is, without the `gc_set_top_of_stack` pair this fails (if using Kinc from Kha) as soon as you input one unicode character, whereas it works with no errors with them. I took that pair of functions from https://github.com/Kode/khacpp/blob/master/docs/ThreadsAndStacks.md#not-called-from-main — but, to be honest, I'm not sure why they are needed in any extend more than *use them if you are doing Haxe things in a callback not called from main*. :man_shrugging: 

Since this has really nothing to do with Kinc directly, I think that adding an `#ifdef KHA` would be OK, but I'm not sure if you would be OK with that.

Any suggestions? :thinking:

**Comment by RobDangerous** [comment]
Sorry, I'm not ok with any #ifdef kha in Kinc. It also wouldn't really solve the problem here, it would merely hide it so it can come back later in really ugly ways - because the root problem here seems to be that the code is called from a different thread which is sadly how Android Java input things work.

**Comment by RobDangerous** [comment]
Fixed the threading but I was too lazy to test it.

**Pull request merged**
