### PR TITLE
Fix https://github.com/Kode/Kha/issues/978

### PR DESCRIPTION
**Pull request by Joncom**

### CODE REVIEW

**Comment by RobDangerous** [comment]
I see a size and a position in pixel coordinates in there - might those be problematic on different devices?

**Comment by Joncom** [comment]
I suspect not because:

- those auto-generated numbers don’t seem particularly relevant to the iPhone 5S specifically
- the rectangle appears to have an auto-resize flag so it fills any screen (otherwise it wouldn’t even fill my iPhone 5S by the look of it)
- this is just used as a launch screen and should not factor into the actual app dimensions because our apps are not built with storyboards

But I’m speculating. Maybe someone with a different iOS device could vouch that Kha apps still launch/look normal after this patch?

**Comment by RobDangerous** [comment]
I'll give it a try on the weekend (I haz an iPad Mini 2 thing).

**Comment by RobDangerous** [comment]
With this merged is #358 still required?

**Comment by Joncom** [comment]
I'll get back to you on that...

**Comment by Joncom** [comment]
I’m not sure if it’s still needed. And I haven’t been working with Kha
recently.

**Pull request merged**
