### PR TITLE
DirectX9 now works correctly with multiple rendertargets

### PR DESCRIPTION
**Pull request by jefvel**
(Y) Works now!

I'll make the backbuffer static for non resizable windows tomorrow.

### CODE REVIEW

**Comment by jefvel** [comment]
aw no my bad, it didn't solve a thing

**Comment by jefvel** [comment]
it works in debug, but not release. strange. so it's 50% complete? I'll investigate

**Comment by jefvel** [comment]
some weird stuff is happening. this works if you add a trace to Kha/Backends/Kore/kha/kore/graphics4/Graphics.hx, line 592 like this:

`
    public function begin(additionalRenderTargets: Array<Canvas> = null): Void {
        if (target == null) {
            trace("I am needed due to some kind of optimization?");
            renderToBackbuffer();
        } else {
            renderToTexture(additionalRenderTargets);
        }
    }
`

Weird!

**Comment by luboslenco** [comment]
Hm, can you check the generated cpp code for both cases to see what is going on?

**Comment by jefvel** [comment]
http://hastebin.com/gopibotowi.coffee
Here's the generated code for the working version and non working one.
I don't see what is wrong.

**Comment by luboslenco** [comment]
Guess there is some uninitialized variables business going on.

**Comment by jefvel** [comment]
How should I troubleshoot it?

**Comment by jefvel** [comment]
it's 
`hx::SourceInfo(HX_("Graphics.hx", b3, 32, 67, 7f), 592, HX_("kha.kore.graphics4.Graphics", 5d, 72, 20, bb),HX_("begin",29,ea,55,b0));`
that makes it work in release. Not sure where to go from there

**Comment by jefvel** [comment]
Fixed!

**Pull request merged**
