### PR TITLE
Linux gamepad support

### PR DESCRIPTION
**Pull request by guzzard**
Hi @RobDangerous,

This is basically a heavily modified version of the joystick/gamepad implemenation found in SFML. I have tested it using a wireless Xbox 360 controller and two other older USB gamepads. Everything works fine as far as I can tell.

- GamepadManager.h/cpp
  - Udev implementation detecting connecting/disconnecting gamepads, checking name etc
  - Manages/updates all the gamepads
  - LinuxGamepad struct describing a gamepad
- System.cpp
  - Instantiation, gamepad manager updating, deletion of gamepad manager added
- korefile.js
  - Added udev build dependency

Please review and give me your feedback. I'm sure there are things that need to be fixed. Thanks!

### CODE REVIEW

**Comment by guzzard** [comment]
@RobDangerous if libudev-dev is added to the apt packages in the travis-ci config the build should succeed.

**Comment by luboslenco** [comment]
🎉 👍

**Comment by RobDangerous** [comment]
Uh, we can't just grab SFML sources. According to the SFML license we'd have to include their license file in source distributions which I don't want to do. Sorry. I'll tread this as documentation for a new implementation.

**Comment by guzzard** [comment]
@RobDangerous, are you sure that would be required? Perhaps I used the wrong words to describe the implementation. I would say it's inspired by the SFML implementation. It's not a straight copy of the SFML source with a few modifications. This implementation is far simpler than the one in SFML. I would not count this as an "altered source version", and not a SFML "source distribution", so no SFML license need to be included anywhere?

**Comment by guzzard** [comment]
Ok understood. Closed the pull req.

**Pull request closed without merging**
