### PR TITLE
[Objc] language/load_url

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by RobDangerous** [comment]
For the language we need the ISO 639-1 string (the small two letter thing ala "en",...). Does that code do that? Apple's documentation doesn't tell me any details about the preferredLanguages array.

**Comment by RblSb** [comment]
No, it return extended format (en-EN)... Maybe just do substr on Haxe side?

**Comment by RblSb** [comment]
Ah, right, Kinc should have same spec. Will fix it.

**Comment by RobDangerous** [comment]
Use this code from some secret backend as reference (we should also copy it to the Windows backend):
```
static char language[3];

const char *kinc_language() {
	wchar_t locale[64];
	GetUserDefaultLocaleName(locale, 63);
	language[0] = locale[0];
	language[1] = locale[1];
	language[2] = 0;
	return language;
}
```

**Pull request merged**
