### PR TITLE
Split audio stream into left and right channel

### PR DESCRIPTION
**Pull request by CatCuddler**
Split audio data. Left and right channel are in s16 audio stream, alternating.

### CODE REVIEW

**Comment by CatCuddler** [comment]
In the moment, audio data will be linear interpolated. I also implemented a hermite interpolation method, but i can't hear the difference.

**Comment by RobDangerous** [comment]
Cool. We can look for some low-sample-rate sound files to test it.

**Comment by CatCuddler** [comment]
I will try to test it. In BlocksFromHeaven it works well.

**Comment by CatCuddler** [comment]
Ok. I tested it with audio sampled at 8, 16 and 48 kHz (44.1 kHz has anyway worked already).

**Comment by RobDangerous** [comment]
Thanks! Will merge soon, just have to make sure the changes to the Sound object won't get Kha confused.

**Pull request merged**
