### PR TITLE
Fix segmentation fault in Linux when cutting/copying big strings.

### PR DESCRIPTION
**Pull request by Sanva**
Only happened if you have a cut/copy listener defined and try to cut/copy a string bigger than 4096 bytes — with different situations about that segmentation fault depending on debug/release build configuration and also how big the more-than-4096-bytes string was.

### CODE REVIEW

**Comment by Sanva** [comment]
By the way, the same error is also in Kha — I'll make another pull request there soon.

**Comment by RobDangerous** [comment]
Hey, no mallocs in Kinc, please.

**Comment by Sanva** [comment]
@RobDangerous any reason for that?

**Comment by RobDangerous** [comment]
I try to get Kinc to be allocation-free after it's initialized so it's more reliable.

**Comment by Sanva** [comment]
I understand.

So,what about an hybrid solution? I can recover the static `char[4096]` and use that, just like without this pull request — **but** checking sizes when copying and using `malloc` **only** if there is a bigger than 4096 bytes string.

**Comment by RobDangerous** [comment]
But... you already did a hybrid solution. Whether you initially malloc in kinc_init or use static memory isn't important.
I need to read up on Linux clipboards again, I'm not entirely sure why we even need that string. If we can't come up with a proper fix, we will put dynamic clipboard strings behind a define and make it cut off the string and print a warning when the define is off (which would be the default).

**Comment by Sanva** [comment]
> But... you already did a hybrid solution.

I'm not sure if I've explained myself... By *hybrid* I mean using the previous solution (in Kinc `master`) and this one in this PR, at the same time: The new proposal would be about having the original 4096 static buffer, and not using `malloc` *at all*, **never**, if the cut/copied string never goes beyond the 4096 limit. If it does, `malloc` would be used — and I could even check if `malloc` fails, and assume in that case that we simply can't cut/copy that entire string in that system, so reverting to static buffer cutting of the string and issuing a warning.

> If we can't come up with a proper fix, we will put dynamic clipboard strings behind a define [...]

That would look good to me.

By the way, Windows appears to have the *cut of the string* approach, but without the warning → https://github.com/Kode/Kinc/blob/master/Backends/System/Windows/Sources/kinc/backend/system.cpp#L1267-L1279

> I need to read up on Linux clipboards again [...]

Now that I think more about this issue... I think a proper fix for this may be the same fix for #602 .

**Comment by RobDangerous** [comment]
You did make yourself clear, it's just not changing anything. The problem with malloc is that 99,99% of the time there's not much of a problem but the circumstances for the remaining 0.01% are complex. By calling malloc only if x, you still have the same situation - a program that under certain cirumstances in very rare situations doesn't behave correctly.
And yes, Windows has a similar issue but there I could fix it easily by introducing a global scratch buffer - which I plan to do anyway. But on the Linux side the lifetime of the string is unclear.
Figuring out how #602 is normally handled might indeed help here, too - maybe we aren't even supposed to put things into an internal buffer.

**Comment by ghost** [comment]
i believe x11 clipboard does not store selection by itself, so owner needs to hold on to that data, and if program exits, there is nothing to paste, so #602 is just expected behaviour

from [X Selections, Cut Buffers, and Kill Rings](https://www.jwz.org/doc/x-cut-and-paste.html):


>  Asserting ownership of a selection doesn't actually transfer data. 
>  When you want to copy text from application A to application B, it goes like this:
> 
>  Copy text in program A: program A asserts selection ownership.
>  Paste text in program B: program B notes that program A owns the selection.
>  program B asks A for the text.
>  program A responds, and sends the text to program B.
>  program B pastes the response.

**Comment by ghost** [comment]
From what i can tell, there is a concept of [Clipboard Manager Specification](https://www.freedesktop.org/wiki/ClipboardManager/), but i can't find much information about it, most of information i found is about a decade old, or talks mostly about automated solutions in GTK and Qt. 

After some investigation, i found that there is a program called xclipboard (xorg-xclipboard in archlinux repos), which, while running, without any modification to the code, solves #602, so i think it's up to OS/DE setup, but i am really not sure.

**Comment by RobDangerous** [comment]
So when Linux really requires us to keep the buffer around ourselves I'm afraid there's no good way around allocating like that, so I'm merging this after all. Thanks a lot for looking into it in detail!

**Pull request merged**
