### PR TITLE
Refactor Linux backend.

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
Wayland support.
Runtime detection of wayland vs x11 and dynamic loading of relevant libraries/functions.
Actual support of multiple windows for both wayland and x11.
(But only for OpenGL right now, the G5 backends will need some refactoring before multi window support is possible for them.)

Todo-list:
- [x] Fullscreen for Wayland.
- [x] Clipboard support for Wayland.
- [x] Client side decorations for Wayland
- [x] Drag and drop for Wayland
- [x] Eraser/stylus support (For X11 I can just copy the old code and hope it works, but I don't have the hardware to test it)
- [x] Pointer lock for Wayland 

(Don't merge this just yet, I probably broke a few things along the way, and have not tested everything yet.)

### CODE REVIEW

**Comment by RobDangerous** [comment]
Oho, skimmed it and it looks very good to me so far (apart from half of the tests failing but we can work that out).

**Comment by Apprentice-Alchemist** [comment]
So. Wayland client side decorations.
Currently Mutter (the GNOME compositor) does not support them. (https://gitlab.gnome.org/GNOME/mutter/-/issues/217)
Enlightenment does not support them either.
Kwin (KDE Plasma's compositor) and Sway do support them.
There are a few options:
1. Don't implement them.
Pros: Nothing to do on our side
Cons: GNOME users can't resize/move/minimize/maximize windows with their mouse.
2. Draw our own decorations
Pros: GNOME users can resize/move/minimize/maximize windows
Cons: It won't look as good as X11/GTK, and it'll be out of place compared with "native" apps.
3. Use libdecor (https://gitlab.gnome.org/jadahl/libdecor)
Pros: Less work than option 2, and might look better than our own decorations.
Cons: External dependency.
(Note: I have no idea how well libdecor actually works, so it might not be an option at all.)

**Comment by RobDangerous** [comment]
libdecor's license is not compatible. Looks like doing our own where there are none is the only option.

**Comment by Apprentice-Alchemist** [comment]
I think this PR is ready.
All the features have been implemented (unless I missed something).
Not everything has been tested though (in particular the pen/eraser things, since I don't have the hardware). 

Multiple windows work, but only with OpenGL right now, the Vulkan (and other G5) backends need some updates to support multiple windows. (But that's for another time.)

There's even some not too horrible client side decorations for Wayland.

**Comment by RobDangerous** [comment]
Super cool, in it goes...

**Pull request merged**
