### PR TITLE
Ndk helper update

### PR DESCRIPTION
**Pull request by RblSb**
Potential fix for `ANativeWindow_setBuffersGeometry` crash (no call no crash, no pain no gain). At least should works same. See second commit.

### CODE REVIEW

**Comment by RobDangerous** [comment]
Ah, uhm, same as with the node_modules pull request - please don't, create an issue instead and point me to the update. In pull request form I can't really see what's going on (plus this probably deletes the changes I did to that code).

**Comment by RblSb** [comment]
Nope, first commit is only handmade space changes. Second is actual update without removing Kore things.

**Comment by RobDangerous** [comment]
Nope nope, looks like your removed 4be41a8f and dd46adac.

**Comment by RblSb** [comment]
Yes, but this is second commit :)
I can return dave change to this PR, if it's ok for you (i think saving new code style would be better for next file updates). `#include <string.h>` is same here, right?

**Comment by RobDangerous** [comment]
As I said, please don't send things like this in a pull request.

**Pull request closed without merging**
